name:                astar-monad
version:             0.3.0.0
github:              "ChrisPenner/astar-monad"
license:             BSD3
author:              "Chris Penner"
maintainer:          "christopher.penner@gmail.com"
copyright:           "Chris Penner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/astar-monad#readme>

dependencies:
- base >= 4.7 && < 5
- logict
- logict-state
- mtl

ghc-options:
  - -Wall
  - -Wno-name-shadowing

library:
  source-dirs: src

tests:
  astar-monad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - astar-monad
    - hspec
    - lens
